### ISSUE TITLE
Route with name "login" not found 

### ISSUE THREAD

**Issue by mishkeTz** [coolcsn/CsnAuthorization#18]
I have a problem 
Fatal error: Zend\Mvc\Router\Exception\RuntimeException: Route with name "login" not found in C:\wamp\www\Zend\vendor\zendframework\zend-view\src\Helper\Navigation\AbstractHelper.php on line 170

I have already installed csnUser, CsnAuthorization and now CsnAclNavigation throw an error. 
When I include 
<?php echo $this->navigation('navigation')->menu()->setUlClass('nav navbar-nav'); ?> 
or 
<?php echo $this->navigation('navigation')->menu(); ?> I get an error, when i remove It than it's fine.
I don't know why. I replace line 40-42 in layout.phtml with this code

**Comment by wingman007** [comment]
Hello,

The problem is in the "routes". Take a look the configuration file for CsnAclNavigation https://github.com/coolcsn/CsnAclNavigation/blob/master/config/navigation.global.php.dist
You should move this file to your config/autoload folder and rename it to navigation.global.php.
This file is more like an example. There is no route "login" defined in any module. I think this is the reason for the error you are getting. Try to comment  lines 20 to 27 https://github.com/coolcsn/CsnAclNavigation/blob/master/config/navigation.global.php.dist#L20-L27

The code in Layout.phtml is not a problem. 

Just concentrate your attention on https://github.com/coolcsn/CsnAclNavigation/blob/master/config/navigation.global.php.dist  which should be in your config/autoload folder of your app and renamed to navigation.global.php. Make sure the routes you mention in this file exist. They are defined in modeule.congig.php files of the modules. I checked the CsnUser and I can tell the coleagues for some reason didn't defined the route "login". So we are trying to use a route which doesn't exist. I think instead of login you can use a route by  the name "user-index". https://github.com/coolcsn/CsnUser/blob/master/config/module.config.php#L25

We will check again the modules to make sure there are no such errors.

I hope this helps! :)
